import type { Hotspot, Suggestion, LLMAnalysis } from '@realbench/shared';

const GITHUB_API = 'https://api.github.com';
const COMMENT_MARKER = '<!-- realbench-profiling-result -->';

type CommentContext = {
  repo: string;
  prNumber: number;
  token: string;
};

type ProfilingResult = {
  runId: string;
  commitSha: string;
  branch: string;
  buildType: string;
  dashboardUrl: string;
  projectUrl: string;
  hotspots: Hotspot[];
  analysis: LLMAnalysis;
  durationMs: number | null;
};

function renderImpactBadge(impact: string): string {
  if (impact === 'high') return '🔴 High';
  if (impact === 'medium') return '🟡 Medium';
  return '🟢 Low';
}

function renderHotspotsTable(hotspots: Hotspot[]): string {
  const top = hotspots.slice(0, 5);
  if (top.length === 0) return '_No hotspots detected._';

  const rows = top
    .map(
      (h) =>
        `| \`${h.symbol}\` | ${h.selfPct.toFixed(1)}% | ${h.totalPct.toFixed(1)}% | ${h.callCount.toLocaleString()} |`
    )
    .join('\n');

  return `| Function | Self% | Total% | Calls |\n|---|---|---|---|\n${rows}`;
}

function renderSuggestions(suggestions: Suggestion[]): string {
  if (suggestions.length === 0) return '_No optimisation suggestions._';

  return suggestions
    .slice(0, 3)
    .map((s) => {
      const loc = s.file ? ` — \`${s.file}${s.line ? `:${s.line}` : ''}\`` : '';
      return `**${s.rank}. ${renderImpactBadge(s.impact)}**${loc}\n> ${s.problem}\n> 💡 ${s.fix}${s.estimatedSpeedup ? ` _(~${s.estimatedSpeedup})_` : ''}`;
    })
    .join('\n\n');
}

export function buildComment(result: ProfilingResult): string {
  const { runId, commitSha, branch, buildType, dashboardUrl, projectUrl, hotspots, analysis, durationMs } = result;

  const regressionBanner = analysis.regressionDetected
    ? '> ⚠️ **Regression detected** — performance has regressed compared to baseline.\n\n'
    : '';

  const sha = commitSha.slice(0, 7);
  const duration = durationMs != null ? `${(durationMs / 1000).toFixed(1)}s` : 'N/A';

  return `${COMMENT_MARKER}
## 🔬 RealBench Profiling Results

${regressionBanner}| | |
|---|---|
| **Commit** | \`${sha}\` (\`${branch}\`) |
| **Build** | \`${buildType}\` |
| **Duration** | ${duration} |
| **Run ID** | \`${runId}\` |

### 🔥 Top Hotspots

${renderHotspotsTable(hotspots)}

### 💡 Optimisation Suggestions

${renderSuggestions(analysis.suggestions)}

[📈 Open Full Report in RealBench Dashboard](${dashboardUrl}) · [🗂 View Project](${projectUrl})

<sub>Generated by [RealBench](https://realbench-web.fly.dev) · ${new Date().toUTCString()}</sub>
`;
}

async function githubRequest(
  method: string,
  path: string,
  token: string,
  body?: unknown
): Promise<Response> {
  return fetch(`${GITHUB_API}${path}`, {
    method,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
      'Content-Type': 'application/json',
      'User-Agent': 'RealBench-Profiler/1.0',
    },
    body: body != null ? JSON.stringify(body) : undefined,
  });
}

export async function postOrUpdatePrComment(
  ctx: CommentContext,
  body: string
): Promise<string | null> {
  const [owner, repo] = ctx.repo.split('/');
  if (!owner || !repo) return null;

  const listRes = await githubRequest(
    'GET',
    `/repos/${owner}/${repo}/issues/${ctx.prNumber}/comments?per_page=100`,
    ctx.token
  );

  if (!listRes.ok) {
    console.error(`GitHub list comments failed: ${listRes.status} ${await listRes.text()}`);
    return null;
  }

  const comments = (await listRes.json()) as Array<{ id: number; body: string }>;
  const existing = comments.find((c) => c.body.includes(COMMENT_MARKER));

  if (existing) {
    const updateRes = await githubRequest(
      'PATCH',
      `/repos/${owner}/${repo}/issues/comments/${existing.id}`,
      ctx.token,
      { body }
    );
    if (!updateRes.ok) {
      console.error(`GitHub update comment failed: ${updateRes.status} ${await updateRes.text()}`);
      return null;
    }
    const updated = (await updateRes.json()) as { id: number };
    return String(updated.id);
  }

  const createRes = await githubRequest(
    'POST',
    `/repos/${owner}/${repo}/issues/${ctx.prNumber}/comments`,
    ctx.token,
    { body }
  );

  if (!createRes.ok) {
    console.error(`GitHub create comment failed: ${createRes.status} ${await createRes.text()}`);
    return null;
  }

  const created = (await createRes.json()) as { id: number };
  return String(created.id);
}

export async function postPendingComment(ctx: CommentContext, commitSha: string): Promise<string | null> {
  const sha = commitSha.slice(0, 7);
  const body = `${COMMENT_MARKER}
## 🔬 RealBench Profiling Results

⏳ Profiling \`${sha}\` is in progress…

<sub>Generated by [RealBench](https://realbench.dev)</sub>
`;
  return postOrUpdatePrComment(ctx, body);
}
